apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build
      taskRef:
        name: build-image
      workspaces:
        - name: source
          workspace: shared-workspace
